#pragma once

#define MOD_COMM_PUBLIC			L"通讯Public"
#define MEMORY_TAG_COMM_PUBLIC	'LPMC'															// CMPL
#define SIOCTL_TYPE				0x4000
#define IOCTL_UM_START			CTL_CODE(SIOCTL_TYPE, 0xC00, METHOD_IN_DIRECT, FILE_ANY_ACCESS)	// 40003000
#define IOCTL_UM_STOP			CTL_CODE(SIOCTL_TYPE, 0xC01, METHOD_IN_DIRECT, FILE_ANY_ACCESS)	// 40003004
#define IOCTL_UM_DIR_ADD		CTL_CODE(SIOCTL_TYPE, 0xC02, METHOD_IN_DIRECT, FILE_ANY_ACCESS)	// 40003008
#define IOCTL_UM_DIR_DELETE		CTL_CODE(SIOCTL_TYPE, 0xC03, METHOD_IN_DIRECT, FILE_ANY_ACCESS)	// 4000300c
#define IOCTL_UM_DIR_CLEAR		CTL_CODE(SIOCTL_TYPE, 0xC04, METHOD_IN_DIRECT, FILE_ANY_ACCESS)	// 40003010
#define IOCTL_UM_PROC_ADD		CTL_CODE(SIOCTL_TYPE, 0xC05, METHOD_IN_DIRECT, FILE_ANY_ACCESS)	// 40003014
#define IOCTL_UM_PROC_DELETE	CTL_CODE(SIOCTL_TYPE, 0xC06, METHOD_IN_DIRECT, FILE_ANY_ACCESS)	// 40003018
#define IOCTL_UM_PROC_CLEAR		CTL_CODE(SIOCTL_TYPE, 0xC07, METHOD_IN_DIRECT, FILE_ANY_ACCESS)	// 4000301c

typedef enum _DIR_CONTROL_TYPE
{
	DIR_CONTROL_TYPE_NULL	= 0x00000000,
	DIR_CONTROL_TYPE_ACCESS = 0x00000001,
	DIR_CONTROL_TYPE_HIDE	= 0x00000002
} DIR_CONTROL_TYPE, *PDIR_CONTROL_TYPE, *LPDIR_CONTROL_TYPE;

typedef struct _COMM_INFO
{
	WCHAR						wchCheck[MAX_PATH];

	union
	{
		struct
		{
			ULONG				ulPid;		 
		} Proc;

		struct
		{
			WCHAR				wchFileName[MAX_PATH];
			DIR_CONTROL_TYPE	DirControlType;
		} Dir;
	};
} COMM_INFO, *PCOMM_INFO, *LPCOMM_INFO;
