#pragma once

#define MOD_COMM_PUBLIC			L"通讯Public"
#define MEMORY_TAG_COMM_PUBLIC	'LPMC'															// CMPL
#define SIOCTL_TYPE				0x4000
#define IOCTL_UM_START			CTL_CODE(SIOCTL_TYPE, 0xC00, METHOD_BUFFERED, FILE_ANY_ACCESS)	// 40003000
#define IOCTL_UM_STOP			CTL_CODE(SIOCTL_TYPE, 0xC01, METHOD_BUFFERED, FILE_ANY_ACCESS)	// 40003004
#define IOCTL_UM_DIR_ADD		CTL_CODE(SIOCTL_TYPE, 0xC02, METHOD_BUFFERED, FILE_ANY_ACCESS)	// 40003008
#define IOCTL_UM_DIR_GET		CTL_CODE(SIOCTL_TYPE, 0xC03, METHOD_BUFFERED, FILE_ANY_ACCESS)	// 4000300c
#define IOCTL_UM_DIR_DELETE		CTL_CODE(SIOCTL_TYPE, 0xC04, METHOD_BUFFERED, FILE_ANY_ACCESS)	// 40003010
#define IOCTL_UM_DIR_CLEAR		CTL_CODE(SIOCTL_TYPE, 0xC05, METHOD_BUFFERED, FILE_ANY_ACCESS)	// 40003014
#define IOCTL_UM_PROC_ADD		CTL_CODE(SIOCTL_TYPE, 0xC06, METHOD_BUFFERED, FILE_ANY_ACCESS)	// 40003018
#define IOCTL_UM_PROC_GET		CTL_CODE(SIOCTL_TYPE, 0xC07, METHOD_BUFFERED, FILE_ANY_ACCESS)	// 4000301c
#define IOCTL_UM_PROC_DELETE	CTL_CODE(SIOCTL_TYPE, 0xC08, METHOD_BUFFERED, FILE_ANY_ACCESS)	// 40003020
#define IOCTL_UM_PROC_CLEAR		CTL_CODE(SIOCTL_TYPE, 0xC09, METHOD_BUFFERED, FILE_ANY_ACCESS)	// 40003024
#define REQUEST_PACKET_VERSION	0x1
#define REPLY_PACKET_VERSION	0x1

typedef enum _DIR_CONTROL_TYPE
{
	DIR_CONTROL_TYPE_NULL	= 0x00000000,
	DIR_CONTROL_TYPE_ACCESS = 0x00000001,
	DIR_CONTROL_TYPE_HIDE	= 0x00000002
} DIR_CONTROL_TYPE, *PDIR_CONTROL_TYPE, *LPDIR_CONTROL_TYPE;

typedef struct _COMM_INFO
{
	union
	{
		struct
		{
			ULONG				ulPid;
		} Proc;

		struct
		{
			DIR_CONTROL_TYPE	DirControlType;
			WCHAR				wchFileName[MAX_PATH];
		} Dir;
	};
} COMM_INFO, *PCOMM_INFO, *LPCOMM_INFO;

typedef struct _REQUEST_PACKET
{
	ULONG		ulVersion;
	ULONG		ulType;
	COMM_INFO	CommInfo;
} REQUEST_PACKET, *PREQUEST_PACKET, *LPPREQUEST_PACKET;

typedef struct _REPLY_PACKET
{
	ULONG		ulVersion;
	ULONG		ulCount;
	COMM_INFO	CommInfo[1];
} REPLY_PACKET, *PREPLY_PACKET, *LPREPLY_PACKET;

static LPWSTR g_lpCommPortName	= L"\\CommPort";
static LPWSTR g_lpConnectionCtx	= L"38f873n39873jof783jo9823hjoi2h9hjnf9";
